angular.module('rvConstants')
  .constant('COMMON', {
    accredited: 'Accredited',
    address: 'Address',
    capacity: 'Capacity',
    childCareTypes: ['Child Care Facility', 'Child Care Facility - Mildly ill Children', 'Large Family Child Care Home', 'Licensed Family Day Care Home', 'Registered Family Day Care Home', 'Religious Exempt Facility', 'Family Day Care Home'],
    curriculum: 'Curriculums',
    delimeter: '|',
    email: 'Email',
    facilityOpened: 'Facility Opened',
    facilityType: 'Facility Type',
    description: 'About Us',
    fax: 'Fax #',
    goldSeal: 'State Quality Program',
	hoursOfOp: 'Operating Hours',
    leadAdmin: 'Lead Administrator',
    licenseExp: 'License Expiration',
    licenseNum: 'State License/Registration #',
    longDays: ['monday','tuesday','wednesday','thursday','friday','saturday','sunday'],
    NA: 'N/A',
    N: 'N',
    no: 'No',
	notApplicable: 'Not applicable',
    notAvailable: 'Not available',
    phone: 'Phone #',
    shortDays: ['mon','tue','wed','thu','fri','sat','sun'],
    website: 'Website',
    Y: 'Y',
    yes: 'Yes',
    aboutus: 'About Us'
  });